"""HL7 FHIR R4 export of one prediction.

Produces a ``Bundle`` (type ``collection``) with three resources:

* ``Patient``          - pseudonymous only (an identifier, no name or birth date),
* ``Observation``      - the predicted class, one component per class probability,
* ``DiagnosticReport`` - status *preliminary*, LOINC 24590-2 (MR Brain), links the
                         Observation and carries a printable HTML copy of the report.

Everything is marked preliminary and AI-generated: a clinician must review it.
"""
from __future__ import annotations

import base64
import json
import uuid
from datetime import datetime, timezone

LOCAL_SYSTEM = "urn:neurofed-ai:codes"
PSEUDONYM_SYSTEM = "urn:neurofed-ai:pseudonym"
UCUM = "http://unitsofmeasure.org"


def _uuid() -> str:
    return str(uuid.uuid4())


def build_bundle(*, result: dict, model_kind: str, model_info: dict, pseudonym: str,
                 report_html: str | None = None) -> dict:
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    pid, oid, rid = _uuid(), _uuid(), _uuid()

    patient = {
        "resourceType": "Patient", "id": pid,
        "identifier": [{"system": PSEUDONYM_SYSTEM, "value": pseudonym or "anonymous"}],
        "meta": {"tag": [{"system": LOCAL_SYSTEM, "code": "pseudonymised",
                          "display": "No directly identifying data"}]},
    }

    components = [{
        "code": {"coding": [{"system": LOCAL_SYSTEM, "code": f"prob-{name}", "display": f"Probability: {name}"}],
                 "text": f"Probability of {name}"},
        "valueQuantity": {"value": round(p * 100, 2), "unit": "%", "system": UCUM, "code": "%"},
    } for name, p in result["probabilities"].items()]

    observation = {
        "resourceType": "Observation", "id": oid, "status": "preliminary",
        "category": [{"coding": [{"system": "http://terminology.hl7.org/CodeSystem/observation-category",
                                  "code": "imaging", "display": "Imaging"}]}],
        "code": {"coding": [{"system": LOCAL_SYSTEM, "code": "ai-brain-tumour-class",
                             "display": "AI brain tumour classification"}],
                 "text": "AI-assisted brain tumour classification from MRI"},
        "subject": {"reference": f"urn:uuid:{pid}"},
        "effectiveDateTime": now, "issued": now,
        "valueCodeableConcept": {"coding": [{"system": LOCAL_SYSTEM, "code": result["predicted_class"],
                                             "display": result["predicted_class"]}],
                                 "text": result["predicted_class"]},
        "interpretation": [{"text": "Low confidence" if result["low_confidence"] else "Confidence above threshold"}],
        "method": {"text": f"{model_kind.capitalize()} CNN (NeuroFed AI)"},
        "note": [{"text": "Generated by a research prototype. Not a clinical diagnosis."}],
        "component": components,
    }

    conclusion = (f"AI model ({model_kind}) suggests '{result['predicted_class']}' with "
                  f"{result['confidence'] * 100:.1f}% (uncalibrated) probability. Preliminary, AI-generated result "
                  "for research use; requires review by a qualified clinician.")
    report = {
        "resourceType": "DiagnosticReport", "id": rid, "status": "preliminary",
        "category": [{"coding": [{"system": "http://terminology.hl7.org/CodeSystem/v2-0074",
                                  "code": "RAD", "display": "Radiology"}]}],
        "code": {"coding": [{"system": "http://loinc.org", "code": "24590-2", "display": "MR Brain"}],
                 "text": "MRI brain - AI-assisted screening (NeuroFed AI)"},
        "subject": {"reference": f"urn:uuid:{pid}"},
        "effectiveDateTime": now, "issued": now,
        "result": [{"reference": f"urn:uuid:{oid}"}],
        "conclusion": conclusion,
        "extension": [{"url": "urn:neurofed-ai:model", "valueString": json.dumps(model_info, default=str)}],
    }
    if report_html:
        report["presentedForm"] = [{"contentType": "text/html", "title": "NeuroFed AI screening report",
                                    "data": base64.b64encode(report_html.encode("utf-8")).decode("ascii")}]

    return {
        "resourceType": "Bundle", "id": _uuid(), "type": "collection", "timestamp": now,
        "entry": [{"fullUrl": f"urn:uuid:{r['id']}", "resource": r} for r in (patient, observation, report)],
    }


def to_json(bundle: dict) -> str:
    return json.dumps(bundle, indent=2, ensure_ascii=False)
